[package]
name = "nicu_src"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
jsonwebtoken = "8.1"
serde = { version = "1.0", features = ["derive"] }
rocket = "0.5"

[lib]
path = "lib.rs"  # This tells Cargo that lib.rs is the library target